
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rogvxcslpyamonawibxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvZ3Z4Y3NscHlhbW9uYXdpYnh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTkwMzgsImV4cCI6MjA1OTE3NTAzOH0.wEBqYB2pT0XVqh3ALUKjC3ZX-SFONp4YIsP3hFhCFMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    }
  }
);
